'use strict';

/**
 * Collection of images to be cycled through.
 * Image sizes: at least 1920px wide, less than 5 MB
 */
exports.ImageSets = [
    //0
    require('./imagesets/hallstatt.js').ImageSet,
    //1
    require('./imagesets/paris.js').ImageSet,
    //2
    require('./imagesets/fiordland.js').ImageSet,
    //3
    require('./imagesets/new_york.js').ImageSet,
    //4
    require('./imagesets/venice.js').ImageSet,
    //5
    require('./imagesets/tuscany.js').ImageSet,
    //6
    require('./imagesets/grand_canyon.js').ImageSet,
    //7
    require('./imagesets/san_francisco.js').ImageSet,
    //8
    require('./imagesets/neuschwanstein_castle.js').ImageSet,
    //9
    require('./imagesets/aurora.js').ImageSet,
    //10
    require('./imagesets/bora_bora.js').ImageSet,
    //11
    require('./imagesets/st_petersburg.js').ImageSet,
    //12
    require('./imagesets/meteora.js').ImageSet,
    //13
    require('./imagesets/atlantic_ocean_road.js').ImageSet,
    //14
    require('./imagesets/stockholm.js').ImageSet,
    //15
    require('./imagesets/manarola.js').ImageSet,
    //16
    require('./imagesets/yosemite.js').ImageSet,
    //17
    require('./imagesets/great_wall_of_china.js').ImageSet,
    //18
    require('./imagesets/rio_de_janeiro.js').ImageSet,
    //19
    require('./imagesets/matsumoto_castle.js').ImageSet,
    //20
    require('./imagesets/washington_dc.js').ImageSet,
    //21
    require('./imagesets/toronto.js').ImageSet,
    //22
    require('./imagesets/innsbruck.js').ImageSet,
    //23
    require('./imagesets/chichen_itza.js').ImageSet,
    //24
    require('./imagesets/petra.js').ImageSet,
    //25
    require('./imagesets/london.js').ImageSet,
    //26
    require('./imagesets/forbidden_city.js').ImageSet,
    //27
    require('./imagesets/dubai.js').ImageSet,
    //28
    require('./imagesets/machu_picchu.js').ImageSet,
    //29
    require('./imagesets/angkor_wat.js').ImageSet,
    //30
    require('./imagesets/faroe_islands.js').ImageSet,
    //31
    require('./imagesets/bagan.js').ImageSet,
    //32
    require('./imagesets/reine.js').ImageSet,
    // 33
    require('./imagesets/bologna.js').ImageSet
];
